#!/bin/bash

rpm -i http://mirror.duomenucentras.lt/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
rpm -Uhv http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm



yum -y install mc yum-cron ntp ntsysv wget elinks httpd fontconfig libpng libXau rsync mailx unrar mutt sysstat mutt net-tools
yum -y install php56w php56w-devel php56w-gd php56w-intl php56w-opcache php56w-mysql php56w-pdo php56w-mbstring php56w-mysql php56w-pear php56w-pecl-memcache php56w-pspell php56w-soap php56w-xml php56w-xmlrpc php56w-mcrypt 
yum -y groupinstall Development tools
yum -y install zlib-devel
yum -y update


timedatectl set-timezone Europe/Vilnius
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload
systemctl enable httpd.service
systemctl restart httpd.service

chmod -R 755 /var/www/html

mkdir /mnt/storage
