#!/bin/bash

rpm -i http://mirror.duomenucentras.lt/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
rpm -Uhv http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm



yum -y install mc yum-cron ntp ntsysv wget elinks httpd fontconfig libpng libXau rsync mailx unrar mutt sysstat mutt net-tools
yum install -y php php-devel php-gd php-intl php-mbstring php-mysql php-pear php-pecl-apc php-pecl-memcache php-pspell php-soap php-xml php-xmlrpc php-mcrypt 
yum -y groupinstall Development tools
yum -y install zlib-devel
yum -y update


timedatectl set-timezone Europe/Vilnius
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload
systemctl enable httpd.service
systemctl restart httpd.service

chmod -R 755 /var/www/html

mkdir /mnt/storage
